export const NAVBAR = [
  { id: 1, label: "Rent GPU Computing", href: "/" },
  { id: 4, label: "Powerfull Dedicate Server", href: "/cloud/dedicated" },
  { id: 2, label: "Cloud Mining", href: "/cloud/mining" },
  { id: 3, label: "Cloud Gaming", href: "/cloud/gaming" },
  { id: 5, label: "Anon Node", href: "/cloud/anone" },
  { id: 6, label: "Api Service", href: "/cloud/api-service" },
];

export const datatable = [
  {
    id: "m5gr84i9",
    memory: 5,
    vcpu: 12,
    bandwith: 4,
    storage: "24GB",
    connection: 20,
    monthPrice: 3.4,
    hourPrice: 0.005,
  },
  {
    id: "m5asdgr84i9",
    memory: 5,
    vcpu: 12,
    bandwith: 7,
    storage: "24GB",
    connection: 20,
    monthPrice: 3.4,
    hourPrice: 0.005,
  },
  {
    id: "sdfsdfdsf",
    memory: 5,
    vcpu: 12,
    bandwith: 7,
    storage: "24GB",
    connection: 20,
    monthPrice: 3.4,
    hourPrice: 0.005,
  },
  {
    id: "erfgsdf",
    memory: 5,
    vcpu: 12,
    bandwith: 7,
    storage: "24GB",
    connection: 20,
    monthPrice: 3.4,
    hourPrice: 0.005,
  },
  {
    id: "aeradfa",
    memory: 5,
    vcpu: 12,
    bandwith: 7,
    storage: "24GB",
    connection: 20,
    monthPrice: 3.4,
    hourPrice: 0.005,
  },
  {
    id: "rthgdfg",
    memory: 5,
    vcpu: 12,
    bandwith: 7,
    storage: "24GB",
    connection: 20,
    monthPrice: 3.4,
    hourPrice: 0.005,
  },
  {
    id: "tyhrtdghf",
    memory: 5,
    vcpu: 12,
    bandwith: 7,
    storage: "24GB",
    connection: 20,
    monthPrice: 3.4,
    hourPrice: 0.005,
  },
  {
    id: "tyhfdrtghf",
    memory: 5,
    vcpu: 12,
    bandwith: 7,
    storage: "24GB",
    connection: 20,
    monthPrice: 3.4,
    hourPrice: 0.005,
  },
  {
    id: "tddyhrtghf",
    memory: 5,
    vcpu: 12,
    bandwith: 7,
    storage: "24GB",
    connection: 20,
    monthPrice: 3.4,
    hourPrice: 0.005,
  },
  {
    id: "tyhrddatghf",
    memory: 5,
    vcpu: 12,
    bandwith: 7,
    storage: "24GB",
    connection: 20,
    monthPrice: 3.4,
    hourPrice: 0.005,
  },
  {
    id: "tyhsrtghf",
    memory: 5,
    vcpu: 12,
    bandwith: 7,
    storage: "24GB",
    connection: 20,
    monthPrice: 3.4,
    hourPrice: 0.005,
  },
];

export const adminOrders = [
  {
    username: "John Doe",
    email: "jhondoe@gmail.com",
    image: "/logo.webp",
    wallet: "0x1234567890",
    bandwith: 4,
  },
];
