export const NAVBAR = [
  { id: 1, label: "Rent GPU Computing", href: "/" },
  { id: 2, label: "Cloud Mining", href: "/cloud/mining" },
  { id: 3, label: "Cloud Gaming", href: "/cloud/gaming" },
  { id: 4, label: "cloud desktop", href: "/cloud/desktop" },
  { id: 5, label: "Anon Node", href: "/cloud/anone" },
];

export const datatable = [
  {
    id: "m5gr84i9",
    title: "  1x NVIDIA A100-SXM4-80GB",
    rate: 8.5,
    status: "pending",
    gpu: "0GB/24GB",
    cpu: "2/16",
    speed: "12/80",
  },
  {
    id: "m5asdgr84i9",
    title: "  1x NVIDIA A100-SXM4-80GB",
    rate: 8.5,
    status: "success",
    gpu: "0GB/24GB",
    cpu: "2/16",
    speed: "12/80",
  },
  {
    id: "sdfsdfdsf",
    title: "  1x NVIDIA A100-SXM4-80GB",
    rate: 8.5,
    status: "success",
    gpu: "0GB/24GB",
    cpu: "2/16",
    speed: "12/80",
  },
  {
    id: "erfgsdf",
    title: "  1x NVIDIA A100-SXM4-80GB",
    rate: 8.5,
    status: "success",
    gpu: "0GB/24GB",
    cpu: "2/16",
    speed: "12/80",
  },
  {
    id: "aeradfa",
    title: "  1x NVIDIA A100-SXM4-80GB",
    rate: 8.5,
    status: "success",
    gpu: "0GB/24GB",
    cpu: "2/16",
    speed: "12/80",
  },
  {
    id: "rthgdfg",
    title: "  1x NVIDIA A100-SXM4-80GB",
    rate: 8.5,
    status: "success",
    gpu: "0GB/24GB",
    cpu: "2/16",
    speed: "12/80",
  },
  {
    id: "tyhrtdghf",
    title: "  1x NVIDIA A100-SXM4-80GB",
    rate: 8.5,
    status: "success",
    gpu: "0GB/24GB",
    cpu: "2/16",
    speed: "12/80",
  },
  {
    id: "tyhfdrtghf",
    title: "  1x NVIDIA A100-SXM4-80GB",
    rate: 8.5,
    status: "success",
    gpu: "0GB/24GB",
    cpu: "2/16",
    speed: "12/80",
  },
  {
    id: "tddyhrtghf",
    title: "  1x NVIDIA A100-SXM4-80GB",
    rate: 8.5,
    status: "success",
    gpu: "0GB/24GB",
    cpu: "2/16",
    speed: "12/80",
  },
  {
    id: "tyhrddatghf",
    title: "  1x NVIDIA A100-SXM4-80GB",
    rate: 8.5,
    status: "success",
    gpu: "0GB/24GB",
    cpu: "2/16",
    speed: "12/80",
  },
  {
    id: "tyhsrtghf",
    title: "  1x NVIDIA A100-SXM4-80GB",
    rate: 8.5,
    status: "success",
    gpu: "0GB/24GB",
    cpu: "2/16",
    speed: "12/80",
  },
];

export const adminOrders = [
  {
    username: "John Doe",
    email: "jhondoe@gmail.com",
    image: "/logo.webp",
    wallet: "0x1234567890",
    status: "pending",
  },
];
